apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 728255670123.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 728255670123.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: e78844e9
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
